"""Added UUID to Users.

Revision ID: 1ad9e065242a
Revises: c61626d45f56
Create Date: 2021-09-07 23:58:03.266489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad9e065242a'
down_revision = 'c61626d45f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###
